Repository thijsvanloef/palworld-server-docker, pull requests merged in 2024-01, with the labels that each got.

#71 Changable Query Port
  Dockerfile
  README.md
  scripts/start.sh
Labels: enhancement

#65 fix: added basic yamls for kubernetes support.
  k8s/configmap.yaml
  k8s/deployment.yaml
  k8s/pvc.yaml
  k8s/readme.md
  k8s/secret.yaml
  k8s/service.yaml
Labels: enhancement, help wanted

#95 Added timezone option
  Dockerfile
  README.md
  docker-compose.yml
Labels: enhancement

#91 Minor additions to the k8s configs
  k8s/configmap.yaml
  k8s/deployment.yaml
  k8s/service.yaml
Labels: enhancement, Kubernetes

#98 Graceful stop
  README.md
  scripts/init.sh
Labels: enhancement

#144 Make volume mount hierarchy consistent, implement tickrate
  k8s/configmap.yaml
  k8s/deployment.yaml
Labels: help wanted, Kubernetes

#141 modify deployment and chart for opionated deployment
  chart/templates/deployments.yaml
  chart/values.yaml
  k8s/deployment.yaml
Labels: help wanted, Kubernetes

#175 Allow changing of all config trough ENV
  README.md
  k8s/configmap.yaml
  k8s/deployment.yaml
  scripts/start.sh
Labels: enhancement, help wanted

#190 Updating configmap
  .gitignore
  charts/palworld/Chart.yaml
  charts/palworld/VALUES_SUMMARY.md
  charts/palworld/templates/configmaps.yaml
  charts/palworld/values.yaml
Labels: help wanted, kubernetes

#192 - Fixed wrong property in the service annotation;
  charts/palworld/templates/services.yaml
Labels: kubernetes

#188 optionally delete old backups
  README.md
  scripts/backup.sh
Labels: enhancement

#206 Add Daily Reboot Cronjob (K8s)
  charts/palworld/VALUES_SUMMARY.md
  charts/palworld/templates/configmaps.yaml
  charts/palworld/templates/cronjob.yaml
  charts/palworld/templates/role.yaml
  charts/palworld/templates/rolebinding.yaml
  charts/palworld/templates/serviceaccount.yaml
  charts/palworld/values.yaml
  k8s/examples/cronjob-reboot/cm.yaml
  k8s/examples/cronjob-reboot/cronjob.yaml
  k8s/examples/cronjob-reboot/role.yaml
  k8s/examples/cronjob-reboot/rolebinding.yaml
  k8s/examples/cronjob-reboot/serviceaccount.yaml
  k8s/examples/readme.md
Labels: help wanted, kubernetes

#238 Fix incorrect link in zh-CN and kr README.md
  docs/kr/README.md
  docs/zh-CN/README.md
Labels: waiting for feedback

#236 Update serviceType to ClusterIP
  charts/palworld/values.yaml
Labels: help wanted, kubernetes

#215 Changed backup so only old backup files are deleted
  Dockerfile
  scripts/backup.sh
Labels: waiting for feedback
