Repository thijsvanloef/palworld-server-docker, pull requests merged in 2024-03, with the labels that each got.

#464 Better compatibility for ARM64 hosts
  Dockerfile
  README.md
  docusaurus/docs/getting-started/configuration/server-settings.md
  docusaurus/docs/known-issues/known-issues.md
  scripts/helper_install.sh
  scripts/start.sh
Labels: help wanted

#481 Optimize metadata for docusaurus instance.
  docusaurus/docs/advanced/kubernetes.md
  docusaurus/docs/assets/Palworld_Banner.jpg
  docusaurus/docs/getting-started/configuration/engine-settings.md
  docusaurus/docs/getting-started/configuration/game-settings.md
  docusaurus/docs/getting-started/configuration/server-commands.md
  docusaurus/docs/getting-started/configuration/server-settings.md
  docusaurus/docs/getting-started/quick-setup.md
  docusaurus/docs/guides/discord/discord-webhooks.md
  docusaurus/docs/known-issues/known-issues.md
Labels: documentation, enhancement

#486 fix bug that displays start when server has been stopped
  scripts/start.sh
Labels: bug

#490 Allow more flexibility in discord webhooks
  Dockerfile
  README.md
  docusaurus/docs/getting-started/configuration/server-settings.md
  scripts/backup.sh
  scripts/discord.sh
  scripts/helper_functions.sh
  scripts/helper_install.sh
  scripts/init.sh
  scripts/player_logging.sh
  scripts/start.sh
Labels: enhancement, help wanted

#494 Templates update
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: enhancement

#495 Fix Discord Variables
  Dockerfile
  README.md
  docusaurus/docs/getting-started/configuration/server-settings.md
  scripts/backup.sh
  scripts/player_logging.sh
Labels: bug

#500 Change Docusaurus to the more easily findable through search engines
  .github/workflows/docusaurus-deploy.yml
  docusaurus/docs/guides/cronjobs/_category_.json
  docusaurus/docs/guides/cronjobs/automatic-reboots.md
  docusaurus/docs/guides/cronjobs/automatic-server-stopping.md
  docusaurus/docs/guides/cronjobs/automatic-updates.md
  docusaurus/docs/guides/update-the-container.md
  docusaurus/i18n/pt-PT/docusaurus-plugin-content-docs/current/getting-started/configuration/server-settings.md
Labels: documentation, enhancement

#502 fix discord backup variable names
  Dockerfile
  README.md
  docusaurus/docs/getting-started/configuration/server-settings.md
Labels: bug

#504 move automatic-server-stopping
  docusaurus/docs/guides/automatic-server-stopping.md
Labels: bug

#510 replace doexit with shutdown
  scripts/helper_functions.sh
Labels: bug

#508 add webhook message flags
  Dockerfile
  README.md
  docusaurus/docs/getting-started/configuration/server-settings.md
  scripts/discord.sh
Labels: waiting for feedback, needs documentation

#513 Add Container version checking
  .github/workflows/release.yml
  Dockerfile
  scripts/helper_functions.sh
  scripts/helper_install.sh
  scripts/start.sh
Labels: enhancement
