Repository thijsvanloef/palworld-server-docker, pull requests merged in 2024-02, with the labels that each got.

#241 Updated README to list macOS as supported platform.
  README.md
  docs/kr/README.md
Labels: documentation

#246 [Kubernetes] backup before a container is terminated
  charts/palworld/templates/deployments.yaml
Labels: help wanted, kubernetes

#251 fix: swap image.name to image.repository
  charts/palworld/Chart.yaml
  charts/palworld/VALUES_SUMMARY.md
  charts/palworld/templates/deployments.yaml
  charts/palworld/values.yaml
Labels: help wanted, kubernetes

#303 Enable yamllint on whole repo
  .github/FUNDING.yml
  .github/dependabot.yml
  .github/workflows/docker-hub.yml
  .github/workflows/linting.yml
  .github/workflows/release.yml
  .github/workflows/sponsors.yml
  .yamllint.yml
  charts/cr.yaml
  charts/palworld/Chart.yaml
  charts/palworld/values.yaml
  docker-compose.yml
  k8s/configmap.yaml
  k8s/deployment.yaml
  k8s/examples/cronjob-reboot/cm.yaml
  k8s/examples/cronjob-reboot/cronjob.yaml
  k8s/examples/cronjob-reboot/role.yaml
  k8s/examples/cronjob-reboot/rolebinding.yaml
  k8s/examples/cronjob-reboot/serviceaccount.yaml
  k8s/pvc.yaml
  k8s/secret.yaml
  k8s/service.yaml
Labels: enhancement

#306 Add arm64 compatibility
  .github/workflows/docker-hub.yml
  .github/workflows/release.yml
  Dockerfile.arm64
  README.md
  scripts/start.sh
Labels: enhancement

#396 add translate guide
  docusaurus/docs/help-translate/help-translate.md
Labels: documentation, enhancement

#409 Fix always showing: "Game not at target version"
  scripts/helper_install.sh
Labels: bug

#381 Updated isWritable
  scripts/helper_functions.sh
Labels: waiting for feedback

#451 fix wrong description in speed and interval variables
  README.md
  docusaurus/docs/getting-started/configuration/game-settings.md
Labels: bug, documentation

#452 add automatic start/stop documentation
  docusaurus/docs/guides/automatic-server-stopping.md
Labels: documentation

#450 Fix RCON errors during startup
  Dockerfile
  scripts/player_logging.sh
Labels: bug

#461 add default bShowPlayerList=True to PalWorldSettings.ini
  .env.example
  README.md
  docusaurus/docs/getting-started/configuration/game-settings.md
  scripts/compile-settings.sh
  scripts/files/PalWorldSettings.ini.template
Labels: enhancement, needs documentation

#455 Discord: Add support for Mentions
  docusaurus/docs/guides/discord/discord-webhooks.md
  scripts/backup.sh
  scripts/discord.sh
  scripts/helper_functions.sh
  scripts/helper_install.sh
  scripts/init.sh
  scripts/start.sh
  scripts/update.sh
Labels: enhancement

#467 add rcon-wrapper docs
  docusaurus/docs/guides/rcon/_category_.json
  docusaurus/docs/guides/rcon/rcon-wrapper.md
Labels: documentation

#470 update manifest id, fix typo
  README.md
  docusaurus/docs/guides/pinning-game-version.md
  docusaurus/docs/guides/rcon/rcon-wrapper.md
Labels: documentation
